- name: VulnerabilityTesting
  hosts: all
  gather_facts: false
  vars:
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - name: Nmap
      shell: "sh nmap.sh {{ inventory_hostname }}"
      register: nmap_result
  
    - name: Metasploit
      shell: "sh {{ item.script }} {{ inventory_hostname }}"
      with_items:
         - { script: "msploit_win7.sh", group: "Windows7" }
         - { script: "msploit_ws.sh", group: "WindowsServer20082012" }
         - { script: "msploit_linux.sh", group: "Linux" }
      when: inventory_hostname in groups[item.group]
      register: msploit_result
      ignore_errors: true
      
    - name: Nikto
      shell: "sh nikto.sh {{ inventory_hostname }}"
      register: nikto_result
      when: inventory_hostname in groups['Urls']
  
    - name: File-Cleaning (on first host)
      copy:
         content: ""
         dest: "results.docx"
      when: inventory_hostname == ansible_play_hosts_all[0]

        
    - name: Prep Design (on first host)
      shell: "sh design.sh"
      register: design_result
      when: inventory_hostname == ansible_play_hosts_all[0]

    - name: Result_File
      lineinfile:
        path: "results.docx"
        line: "{{ design_result.stdout | default('') }}\n\n{{ nmap_result.stdout }}\n\n{{ nikto_result.stdout | default('') }}\n\n{{ msploit_result.stdout | default('') }}"
      when: inventory_hostname in groups['all']
  
    - name: docx into pdf (on last host)
      become: true
      command: libreoffice --headless --convert-to pdf results.docx
      when: inventory_hostname == ansible_play_hosts_all[-1]

    - name: Send results by email (on last host)
      mail:
        host: smtp.office365.com
        port: 587
        username: "{{ email_username }}"
        password: "{{ email_password }}"
        to: "{{ email_dest }}"
        subject: Results of vulnerability testing
        body: Please find attached the results of the vulnerability testing.
        from: "{{ email_username }}"
        attach:
          - results.pdf
      when: inventory_hostname == ansible_play_hosts_all[-1] and confirmation == 'yes'
